apiVersion: v1
kind: Service
metadata:
  name: ray-head-loadbalancer
spec:
  ports:
  - name: client
    port: 10001
    protocol: TCP
    targetPort: 10001
  selector:
    app: ray-cluster-head
  type: LoadBalancer
