apiVersion: v1
kind: Service
metadata:
  name: triton-servers
  namespace: bbhnet
spec:
  ports:
  - name: http-triton
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc-triton
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: metrics-triton
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: triton-servers
  sessionAffinity: ClientIP
  type: LoadBalancer
