apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-servers 
  labels:
    app: triton-servers
  namespace: bbhnet 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: triton-servers 
  progressDeadlineSeconds: 100
  template:
    metadata:
      labels:
        app: triton-servers 
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.memory
                operator: Gt
                values:
                - "15000"
              - key: nvidia.com/cuda.driver.major
                operator: Gt
                values:
                - '520'
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: tritonserver
        image: ghcr.io/ethanmarx/triton-hermes:latest
        env:
        - name: EXTRA_NV_PATHS
          value: /usr/local/nvidia/lib64:/usr/local/nvidia/bin
        command:
        - export-and-launch-triton
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: "2"
            memory: "30G"
          requests:
            nvidia.com/gpu: 1
            cpu: "2"
            memory: "30G"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        livenessProbe:
          failureThreshold: 30
          initialDelaySeconds: 480
          periodSeconds: 5
          httpGet:
            path: /v2/health/live
            port: http
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 480
          periodSeconds: 10
          httpGet:
            path: /v2/health/ready
            port: http
        readinessProbe:
          initialDelaySeconds: 480 
          failureThreshold: 30
          periodSeconds: 10
          httpGet:
            path: /v2/health/ready
            port: http
